spring:
  application:
    name: coworking-booking

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD} 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Esto hace que el SQL en consola sea legible

  jackson: # Ya no lleva "spring:" delante porque ya estamos dentro del bloque spring
    serialization:
      indent-output: true

springdoc: # en true para ver los endpoint con swagger
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true